name: Automatic Semantic Release

on:
  # workflow_dispatch # manual-only for testing
  push:
    branches:
      - main
jobs:
  new-release:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7 # Checkout our working repository
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@952b14bbc4be87e8458a6ac5926fc655608b1b19 # v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          output-file: 'CHANGELOG.md'
          version-file: 'package.json'
      - name: Debug Changelog Outputs
        run: |
          echo "Skipped: ${{ steps.changelog.outputs.skipped }}"
          echo "Tag: ${{ steps.changelog.outputs.tag }}"
          echo "Clean Changelog: ${{ steps.changelog.outputs.clean_changelog }}"
          echo "Outputs Skipped: ${{ steps.changelog.outputs.skipped }}"
      - name: Auto-Create Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3 # auto create a tag and release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          make_latest: true

